language: python
sudo: false

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - conda info -a

install:
    - conda config --append channels conda-forge
    - conda create -q -n schoty-env --file requirements.txt python=3.6 --yes
    - source activate schoty-env
    - python setup.py develop


script: 
    - py.test -sv schoty_builder
